use ncurses(6) instead of 5 on NixOS
this allows using the same 'nix-shell' to compile pancurses too, without
awkward compile errors, like:
  error[E0425]: cannot find value `BUTTON5_PRESSED` in crate `ncurses`