make undefined symbols more useful in dependants
When a crate(like 'cursive') that uses our crate(ncurses) wants to use
a symbol that we haven't defined because the system installed ncurses
header didn't define, such as BUTTON5_PRESSED, then show a better
compile time error like [1] instead of the usual and more vague one [2]

[1]:
   Compiling cursive v0.20.0 (/Users/user/sandbox/25/ncurses_things/cursive/cursive)
error[E0605]: non-primitive cast: `Your_ncurses_installation_is_too_old_and_it_does_not_have_this_underlined_identifier_defined_in_its_header_file_therefore_the_ncurses_crate_did_not_include_it_because_it_tries_to_be_compatible_however_this_crate_in_which_you_see_the_error_it_needs_the_identifier__If_you_are_on_MacOS_then_use_the_brew_version_of_ncurses_and_set_PKG_CONFIG_PATH_to_the_pkgconfig_dir_from_within_it` as `u32`
   --> cursive/src/backends/curses/n.rs:266:43
    |
266 | ....bstate == ncurses::BUTTON5_DOUBLE_CLICKED as mmask_t)
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ an `as` expression can only be used to convert between primitive types or to coerce to a specific trait object

error[E0308]: `match` arms have incompatible types
   --> cursive/src/backends/curses/n.rs:363:31
    |
357 |           let style = match effect {
    |  _____________________-
358 | |             Effect::Reverse => ncurses::A_REVERSE,
359 | |             Effect::Simple => ncurses::A_NORMAL,
360 | |             Effect::Dim => ncurses::A_DIM,
361 | |             Effect::Bold => ncurses::A_BOLD,
362 | |             Effect::Blink => ncurses::A_BLINK,
    | |                              ---------------- this and all prior arms are found to be of type `u32`
363 | |             Effect::Italic => ncurses::A_ITALIC,
    | |                               ^^^^^^^^^^^^^^^^^ expected `u32`, found `Your_ncurses_installation_is_too_old_and_it_does_not_have_this_underlined_identifier_defined_in_its_header_file_therefore_the_ncurses_crate_did_not_include_it_because_it_tries_to_be_compatible_however_this_crate_in_which_you_see_the_error_it_needs_the_identifier__If_you_are_on_MacOS_then_use_the_brew_version_of_ncurses_and_set_PKG_CONFIG_PATH_to_the_pkgconfig_dir_from_within_it`
364 | |             Effect::Strikethrough => ncurses::A_NORMAL,
365 | |             Effect::Underline => ncurses::A_UNDERLINE,
366 | |         };
    | |_________- `match` arms have incompatible types

error[E0308]: `match` arms have incompatible types
   --> cursive/src/backends/curses/n.rs:377:31
    |
371 |           let style = match effect {
    |  _____________________-
372 | |             Effect::Reverse => ncurses::A_REVERSE,
373 | |             Effect::Simple => ncurses::A_NORMAL,
374 | |             Effect::Dim => ncurses::A_DIM,
375 | |             Effect::Bold => ncurses::A_BOLD,
376 | |             Effect::Blink => ncurses::A_BLINK,
    | |                              ---------------- this and all prior arms are found to be of type `u32`
377 | |             Effect::Italic => ncurses::A_ITALIC,
    | |                               ^^^^^^^^^^^^^^^^^ expected `u32`, found `Your_ncurses_installation_is_too_old_and_it_does_not_have_this_underlined_identifier_defined_in_its_header_file_therefore_the_ncurses_crate_did_not_include_it_because_it_tries_to_be_compatible_however_this_crate_in_which_you_see_the_error_it_needs_the_identifier__If_you_are_on_MacOS_then_use_the_brew_version_of_ncurses_and_set_PKG_CONFIG_PATH_to_the_pkgconfig_dir_from_within_it`
378 | |             Effect::Strikethrough => ncurses::A_NORMAL,
379 | |             Effect::Underline => ncurses::A_UNDERLINE,
380 | |         };
    | |_________- `match` arms have incompatible types

error[E0308]: mismatched types
   --> cursive/src/backends/curses/n.rs:448:9
    |
427 |     match bare_event {
    |           ---------- this expression has type `i32`
...
448 |         ncurses::BUTTON5_RELEASED
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `Your_ncurses_installation_is_too_old_and_it_does_not_have_this_underlined_identifier_defined_in_its_header_file_therefore_the_ncurses_crate_did_not_include_it_because_it_tries_to_be_compatible_however_this_crate_in_which_you_see_the_error_it_needs_the_identifier__If_you_are_on_MacOS_then_use_the_brew_version_of_ncurses_and_set_PKG_CONFIG_PATH_to_the_pkgconfig_dir_from_within_it`

error[E0308]: mismatched types
   --> cursive/src/backends/curses/n.rs:449:11
    |
427 |     match bare_event {
    |           ---------- this expression has type `i32`
...
449 |         | ncurses::BUTTON5_PRESSED
    |           ^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `Your_ncurses_installation_is_too_old_and_it_does_not_have_this_underlined_identifier_defined_in_its_header_file_therefore_the_ncurses_crate_did_not_include_it_because_it_tries_to_be_compatible_however_this_crate_in_which_you_see_the_error_it_needs_the_identifier__If_you_are_on_MacOS_then_use_the_brew_version_of_ncurses_and_set_PKG_CONFIG_PATH_to_the_pkgconfig_dir_from_within_it`

error[E0308]: mismatched types
   --> cursive/src/backends/curses/n.rs:450:11
    |
427 |     match bare_event {
    |           ---------- this expression has type `i32`
...
450 |         | ncurses::BUTTON5_CLICKED
    |           ^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `Your_ncurses_installation_is_too_old_and_it_does_not_have_this_underlined_identifier_defined_in_its_header_file_therefore_the_ncurses_crate_did_not_include_it_because_it_tries_to_be_compatible_however_this_crate_in_which_you_see_the_error_it_needs_the_identifier__If_you_are_on_MacOS_then_use_the_brew_version_of_ncurses_and_set_PKG_CONFIG_PATH_to_the_pkgconfig_dir_from_within_it`

error[E0308]: mismatched types
   --> cursive/src/backends/curses/n.rs:451:11
    |
427 |     match bare_event {
    |           ---------- this expression has type `i32`
...
451 |         | ncurses::BUTTON5_DOUBLE_CLICKED
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `Your_ncurses_installation_is_too_old_and_it_does_not_have_this_underlined_identifier_defined_in_its_header_file_therefore_the_ncurses_crate_did_not_include_it_because_it_tries_to_be_compatible_however_this_crate_in_which_you_see_the_error_it_needs_the_identifier__If_you_are_on_MacOS_then_use_the_brew_version_of_ncurses_and_set_PKG_CONFIG_PATH_to_the_pkgconfig_dir_from_within_it`

error[E0308]: mismatched types
   --> cursive/src/backends/curses/n.rs:452:11
    |
427 |     match bare_event {
    |           ---------- this expression has type `i32`
...
452 |         | ncurses::BUTTON5_TRIPLE_CLICKED => MouseButton::Button5,
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `Your_ncurses_installation_is_too_old_and_it_does_not_have_this_underlined_identifier_defined_in_its_header_file_therefore_the_ncurses_crate_did_not_include_it_because_it_tries_to_be_compatible_however_this_crate_in_which_you_see_the_error_it_needs_the_identifier__If_you_are_on_MacOS_then_use_the_brew_version_of_ncurses_and_set_PKG_CONFIG_PATH_to_the_pkgconfig_dir_from_within_it`

error[E0308]: mismatched types
   --> cursive/src/backends/curses/n.rs:477:9
    |
469 |     match bare_event {
    |           ---------- this expression has type `i32`
...
477 |         ncurses::BUTTON5_PRESSED => f(MouseEvent::WheelDown),
    |         ^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `Your_ncurses_installation_is_too_old_and_it_does_not_have_this_underlined_identifier_defined_in_its_header_file_therefore_the_ncurses_crate_did_not_include_it_because_it_tries_to_be_compatible_however_this_crate_in_which_you_see_the_error_it_needs_the_identifier__If_you_are_on_MacOS_then_use_the_brew_version_of_ncurses_and_set_PKG_CONFIG_PATH_to_the_pkgconfig_dir_from_within_it`

Some errors have detailed explanations: E0308, E0605.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `cursive` (lib) due to 9 previous errors
warning: build failed, waiting for other jobs to finish...
users-iMac:cursive user$

[2]:
   Compiling cursive v0.20.0 (/Users/user/sandbox/25/ncurses_things/cursive/cursive)
error[E0425]: cannot find value `BUTTON5_DOUBLE_CLICKED` in crate `ncurses`
   --> cursive/src/backends/curses/n.rs:266:52
    |
266 | ...bstate == ncurses::BUTTON5_DOUBLE_CLICKED as mmask_t)
    |                       ^^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `BUTTON1_DOUBLE_CLICKED`
    |
   ::: /Users/user/sandbox/25/ncurses_things/cursive/target/debug/build/ncurses-30bbd0fd652fa9fc/out/raw_constants.rs:129:1
    |
129 | pub const BUTTON1_DOUBLE_CLICKED: i32 = 8;
    | ------------------------------------- similarly named constant `BUTTON1_DOUBLE_CLICKED` defined here

error[E0425]: cannot find value `A_ITALIC` in crate `ncurses`
   --> cursive/src/backends/curses/n.rs:363:40
    |
363 |             Effect::Italic => ncurses::A_ITALIC,
    |                                        ^^^^^^^^ not found in `ncurses`

error[E0425]: cannot find value `A_ITALIC` in crate `ncurses`
   --> cursive/src/backends/curses/n.rs:377:40
    |
377 |             Effect::Italic => ncurses::A_ITALIC,
    |                                        ^^^^^^^^ not found in `ncurses`

error[E0531]: cannot find unit struct, unit variant or constant `BUTTON5_RELEASED` in crate `ncurses`
   --> cursive/src/backends/curses/n.rs:448:18
    |
448 |         ncurses::BUTTON5_RELEASED
    |                  ^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `BUTTON1_RELEASED`
    |
   ::: /Users/user/sandbox/25/ncurses_things/cursive/target/debug/build/ncurses-30bbd0fd652fa9fc/out/raw_constants.rs:126:1
    |
126 | pub const BUTTON1_RELEASED: i32 = 1;
    | ------------------------------- similarly named constant `BUTTON1_RELEASED` defined here

error[E0531]: cannot find unit struct, unit variant or constant `BUTTON5_PRESSED` in crate `ncurses`
   --> cursive/src/backends/curses/n.rs:449:20
    |
449 |         | ncurses::BUTTON5_PRESSED
    |                    ^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `BUTTON1_PRESSED`
    |
   ::: /Users/user/sandbox/25/ncurses_things/cursive/target/debug/build/ncurses-30bbd0fd652fa9fc/out/raw_constants.rs:127:1
    |
127 | pub const BUTTON1_PRESSED: i32 = 2;
    | ------------------------------ similarly named constant `BUTTON1_PRESSED` defined here

error[E0531]: cannot find unit struct, unit variant or constant `BUTTON5_CLICKED` in crate `ncurses`
   --> cursive/src/backends/curses/n.rs:450:20
    |
450 |         | ncurses::BUTTON5_CLICKED
    |                    ^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `BUTTON1_CLICKED`
    |
   ::: /Users/user/sandbox/25/ncurses_things/cursive/target/debug/build/ncurses-30bbd0fd652fa9fc/out/raw_constants.rs:128:1
    |
128 | pub const BUTTON1_CLICKED: i32 = 4;
    | ------------------------------ similarly named constant `BUTTON1_CLICKED` defined here

error[E0531]: cannot find unit struct, unit variant or constant `BUTTON5_DOUBLE_CLICKED` in crate `ncurses`
   --> cursive/src/backends/curses/n.rs:451:20
    |
451 |         | ncurses::BUTTON5_DOUBLE_CLICKED
    |                    ^^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `BUTTON1_DOUBLE_CLICKED`
    |
   ::: /Users/user/sandbox/25/ncurses_things/cursive/target/debug/build/ncurses-30bbd0fd652fa9fc/out/raw_constants.rs:129:1
    |
129 | pub const BUTTON1_DOUBLE_CLICKED: i32 = 8;
    | ------------------------------------- similarly named constant `BUTTON1_DOUBLE_CLICKED` defined here

error[E0531]: cannot find unit struct, unit variant or constant `BUTTON5_TRIPLE_CLICKED` in crate `ncurses`
   --> cursive/src/backends/curses/n.rs:452:20
    |
452 |         | ncurses::BUTTON5_TRIPLE_CLICKED => MouseButton::Button5,
    |                    ^^^^^^^^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `BUTTON1_TRIPLE_CLICKED`
    |
   ::: /Users/user/sandbox/25/ncurses_things/cursive/target/debug/build/ncurses-30bbd0fd652fa9fc/out/raw_constants.rs:130:1
    |
130 | pub const BUTTON1_TRIPLE_CLICKED: i32 = 16;
    | ------------------------------------- similarly named constant `BUTTON1_TRIPLE_CLICKED` defined here

error[E0531]: cannot find unit struct, unit variant or constant `BUTTON5_PRESSED` in crate `ncurses`
   --> cursive/src/backends/curses/n.rs:477:18
    |
477 |         ncurses::BUTTON5_PRESSED => f(MouseEvent::WheelDown),
    |                  ^^^^^^^^^^^^^^^ help: a constant with a similar name exists: `BUTTON1_PRESSED`
    |
   ::: /Users/user/sandbox/25/ncurses_things/cursive/target/debug/build/ncurses-30bbd0fd652fa9fc/out/raw_constants.rs:127:1
    |
127 | pub const BUTTON1_PRESSED: i32 = 2;
    | ------------------------------ similarly named constant `BUTTON1_PRESSED` defined here

Some errors have detailed explanations: E0425, E0531.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `cursive` (lib) due to 9 previous errors
warning: build failed, waiting for other jobs to finish...
users-iMac:cursive user$